spring:
  application:
    name: encoding-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: encoding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.netflix.encodingservice.event.VideoUploadedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

# AWS Configuration
aws:
  access-key: YOUR_AWS_ACCESS_KEY_ID
  secret-key: YOUR_AWS_SECRET_ACCESS_KEY
  region: ${AWS_REGION:YOUR_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME:netflix-streaming-videos-082499810116-eu-north-1-an}

# FFmpeg Configuration
ffmpeg:
  path: ${FFMPEG_PATH:C:/ffmpeg/bin/ffmpeg.exe}

# Temp directory for encoding
encoding:
  temp-dir: ${TEMP_DIR:C:/temp/encoding}

management:
  endpoints:
    web:
      exposure:
        include: health,info
