spring:
  application:
    name: video-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8082


# AWS Configuration
aws:
  access-key: YOUR_AWS_ACCESS_KEY_ID
  secret-key: YOUR_AWS_SECRET_ACCESS_KEY
  region: us-east-1
  s3:
    bucket-name: netflix-streaming-videos--636656297213-us-east-1-an


management:
  endpoints:
    web:
      exposure:
        include: health,info
